### ISSUE TITLE
Could you provide entire data set of "standard_uspto_template_library" in the data.zip?

### ISSUE THREAD

**Issue by queliyong** [reymond-group/RingBreaker#1]
Hi,
I'm sure there are 46695 unique templates whose occurrences are beyond 3. But some of them in "standard_uspto_template_library" were deleted for some reason. Could you provide entire data set of "standard_uspto_template_library"? Thank you.

**Comment by A-Thakkar** [comment]
Could you provide more details about you are looking for? The uspto template library we have used in our work is included in the data.zip folder. The template library found with AiZynthFinder can also be used.

For the ringbreaker model the standard library is not used and has been filtered down substantially.

**Comment by queliyong** [comment]
> Could you provide more details about you are looking for? The uspto template library we have used in our work is included in the data.zip folder. The template library found with AiZynthFinder can also be used.
> 
> For the ringbreaker model the standard library is not used and has been filtered down substantially.

I'm looking for the full uspto template library dataset used to train expansion policy. I wanna retrain the expansion policy although trained policies were provided at AiZynthfinder repo. What I'm looking for looks like the "standard_uspto_template_library" dataset in the data.zip folder, which unfortunately is not the entire dataset and is deficient of some templates.

**Comment by A-Thakkar** [comment]
For the Ringbreaker project we do not use the full uspto dataset for training the expansion policy. If you want to retrain on the full dataset then I suggest using the datasets found in the AiZynthFinder repo for the most up to date policies. 

If you want to retrain the expansion policy for ring formations as described in this repo, then i suggest using the ring dataset in the data.zip folder.

Having checked the full_uspto data in the data.zip folder and the full_uspto stored on my machine from the original work the number of reactions contained in both are equivalent. The dataset may vary slightly between the different projects due to slightly different preprocessing methods. 

If the problem you are trying to solve refers to the following issue:
https://github.com/MolecularAI/aizynthfinder/issues/50

I would suggest taking the ringbreaker policy which can be retrained from this repo and using it to predict the disconnection of the cyclic system. I suggest you do not incorporate the ringbreaker policy into the tree search as this will heavily limit the chemistry available, and incorporating it alongside the standard USPTO policy does not lead to performance improvements for two reasons. Firstly there will be a prioritization issue, and secondly the scoring scheme will need to be adapted to account for two different policies and the weighting of each.

Therefore, you could take the cyclic system AiZynthFinder fails to break down using the standard expansion policy, use it as input for ringbreaker, then use the predicted precursors to continue the search using AiZynthFinder. Usually we would handle this issue in an interactive search, however we have not published the code for doing so in the AiZynthFinder module as it is contains references to internal systems.

Hope this helps,

Amol

**Comment by queliyong** [comment]
> For the Ringbreaker project we do not use the full uspto dataset for training the expansion policy. If you want to retrain on the full dataset then I suggest using the datasets found in the AiZynthFinder repo for the most up to date policies.
> 
> If you want to retrain the expansion policy for ring formations as described in this repo, then i suggest using the ring dataset in the data.zip folder.
> 
> Having checked the full_uspto data in the data.zip folder and the full_uspto stored on my machine from the original work the number of reactions contained in both are equivalent. The dataset may vary slightly between the different projects due to slightly different preprocessing methods.
> 
> If the problem you are trying to solve refers to the following issue: [MolecularAI/aizynthfinder#50](https://github.com/MolecularAI/aizynthfinder/issues/50)
> 
> I would suggest taking the ringbreaker policy which can be retrained from this repo and using it to predict the disconnection of the cyclic system. I suggest you do not incorporate the ringbreaker policy into the tree search as this will heavily limit the chemistry available, and incorporating it alongside the standard USPTO policy does not lead to performance improvements for two reasons. Firstly there will be a prioritization issue, and secondly the scoring scheme will need to be adapted to account for two different policies and the weighting of each.
> 
> Therefore, you could take the cyclic system AiZynthFinder fails to break down using the standard expansion policy, use it as input for ringbreaker, then use the predicted precursors to continue the search using AiZynthFinder. Usually we would handle this issue in an interactive search, however we have not published the code for doing so in the AiZynthFinder module as it is contains references to internal systems.
> 
> Hope this helps,
> 
> Amol

Thank  Amol very much for  your helpful and patient reply. It could help me to avoid wasting much time.

**Comment by queliyong** [comment]
> For the Ringbreaker project we do not use the full uspto dataset for training the expansion policy. If you want to retrain on the full dataset then I suggest using the datasets found in the AiZynthFinder repo for the most up to date policies.
> 
> If you want to retrain the expansion policy for ring formations as described in this repo, then i suggest using the ring dataset in the data.zip folder.
> 
> Having checked the full_uspto data in the data.zip folder and the full_uspto stored on my machine from the original work the number of reactions contained in both are equivalent. The dataset may vary slightly between the different projects due to slightly different preprocessing methods.
> 
> If the problem you are trying to solve refers to the following issue: [MolecularAI/aizynthfinder#50](https://github.com/MolecularAI/aizynthfinder/issues/50)
> 
> I would suggest taking the ringbreaker policy which can be retrained from this repo and using it to predict the disconnection of the cyclic system. I suggest you do not incorporate the ringbreaker policy into the tree search as this will heavily limit the chemistry available, and incorporating it alongside the standard USPTO policy does not lead to performance improvements for two reasons. Firstly there will be a prioritization issue, and secondly the scoring scheme will need to be adapted to account for two different policies and the weighting of each.
> 
> Therefore, you could take the cyclic system AiZynthFinder fails to break down using the standard expansion policy, use it as input for ringbreaker, then use the predicted precursors to continue the search using AiZynthFinder. Usually we would handle this issue in an interactive search, however we have not published the code for doing so in the AiZynthFinder module as it is contains references to internal systems.
> 
> Hope this helps,
> 
> Amol

Thank  Amol very much for  your helpful and patient reply. It could help me to avoid wasting much time.

**Comment by queliyong** [comment]
> For the Ringbreaker project we do not use the full uspto dataset for training the expansion policy. If you want to retrain on the full dataset then I suggest using the datasets found in the AiZynthFinder repo for the most up to date policies.
> 
> If you want to retrain the expansion policy for ring formations as described in this repo, then i suggest using the ring dataset in the data.zip folder.
> 
> Having checked the full_uspto data in the data.zip folder and the full_uspto stored on my machine from the original work the number of reactions contained in both are equivalent. The dataset may vary slightly between the different projects due to slightly different preprocessing methods.
> 
> If the problem you are trying to solve refers to the following issue: [MolecularAI/aizynthfinder#50](https://github.com/MolecularAI/aizynthfinder/issues/50)
> 
> I would suggest taking the ringbreaker policy which can be retrained from this repo and using it to predict the disconnection of the cyclic system. I suggest you do not incorporate the ringbreaker policy into the tree search as this will heavily limit the chemistry available, and incorporating it alongside the standard USPTO policy does not lead to performance improvements for two reasons. Firstly there will be a prioritization issue, and secondly the scoring scheme will need to be adapted to account for two different policies and the weighting of each.
> 
> Therefore, you could take the cyclic system AiZynthFinder fails to break down using the standard expansion policy, use it as input for ringbreaker, then use the predicted precursors to continue the search using AiZynthFinder. Usually we would handle this issue in an interactive search, however we have not published the code for doing so in the AiZynthFinder module as it is contains references to internal systems.
> 
> Hope this helps,
> 
> Amol

Thank  Amol very much for  your helpful and patient reply. It could help me to avoid wasting much time.
